12-11-2020 01:58:32 PM: ERROR:Internal Server Error: /c4r0nt3/zendesk/zendeskuser/add/
Traceback (most recent call last):
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/contrib/admin/options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1637, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1568, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/isaialejandro/.local/share/virtualenvs/voireg-H8f3TbEp/lib/python3.8/site-packages/django/contrib/admin/options.py", line 808, in log_addition
    object_repr=str(object),
  File "/Users/isaialejandro/Documents/workSpace/Django/voireg/voi_app/apps/zendesk/models.py", line 16, in __str__
    def __str__(self):
AttributeError: 'ZendeskUserHistory' object has no attribute 'datetime'
